config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'maps#index'
  resources :maps
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   # association
   has_many :maps
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
# frozen_string_literal: true

class MapsController < ApplicationController
  def index
    @maps = Map.all
    @map = Map.new
  end

  def new
    @map = Map.new(map_params)
  end

  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to :root }
        format.js
      else
        format.html { render :new }
        format.js { render :errors}
      end
    end
  end

  def upadate
    @map = Map.find(params[:id])
  end

  def destroy
    @map = Map.find(params[:id])
  end

  private

  def map_params
    params.require(:map).permit(:name, :address, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/maps_helper.rb
# frozen_string_literal: true

module MapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>SpaMap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
  
</html>

app/views/maps/create.js.erb
$('.messages').append("<li class='message'><%= @map.name %></li>");
$('.js-form')[0].reset();

app/views/maps/index.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render "shared/sidebar" %>
    <div id="target" class="col-md-9"></div>
  </div>
</div>
<script src="https://maps.googleapis.com/maps/api/js?language=ja&region=JP&key=<%="#{ENV['API_KEY']}"%>&callback=initMap&libraries=places" async defer></script>
<script>
  var map;
  var count = 0;
  function initMap() {
    'use strict';
    var target = document.getElementById("target")
    var geocoder = new google.maps.Geocoder();
    const search = document.getElementById("search")
    var tokyo = {lat: 35.681167, lng: 139.767052}
    var cl = document.getElementById('cl');
    var reset = document.getElementById('reset')

    map = new google.maps.Map(target, {
      center: tokyo,
      zoom: 15
    });

    searchOnsen();
    dragMarker();

    cl.addEventListener('click', function(){
      if (!navigator.geolocation) {
        alert('Geolocation not supported');
        return;
      }
      navigator.geolocation.getCurrentPosition(function(position) {
        var place = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
        map = new google.maps.Map(target, {
          center: place,
          zoom: 15
        });
        var marker = new google.maps.Marker({
          position: place,
          map: map
        });
        searchOnsen();
        dragMarker();
      },function() {
          alert('位置情報取得に失敗しました');
      });
    });

    search.addEventListener('click', function(){
      geocoder.geocode({
        address: document.getElementById('address').value
      }, function(results, status) {
        if (status !== 'OK') {
          alert('該当する場所がございません。')
          return;
        }
        if (results[0]) {
        map = new google.maps.Map(target, {
            center: results[0].geometry.location,
            zoom: 15
          });
        } else {
          alert('該当する場所がございません。')
          return;
        }
        searchOnsen();
        dragMarker();
      });
    });

    reset.addEventListener('click', () => {
      var parent = document.getElementById('parent');

        if (parent.hasChildNodes()) {
          while(parent.firstChild){
            parent.removeChild(parent.firstChild);
          }
          count = 0;
        } else {
          alert("リストがございません。");
        }
    });
  }

  function searchOnsen(){
    var latlng = map.getCenter();
    var lat = latlng.lat();
    var lng = latlng.lng();
    var service = new google.maps.places.PlacesService(map);
    service.nearbySearch({
      location: {lat: lat, lng: lng},
      radius: 1000,
      keyword: "銭湯",
      language: 'ja',
    },function(results, status) {
      if(status == google.maps.places.PlacesServiceStatus.OK){
        for(var i = 0; i < results.length;i++) {
          var location = results[i].geometry.location;
          var name = results[i].name;
          var geocoder = new google.maps.Geocoder();

          geocoder.geocode({
            location: location
          }, function(results, status) {
            try{
              var adds = results[0].formatted_address.replace("日本、", "");
            } catch(e) {
              var adds = ""
            }

            const infowindow = new google.maps.InfoWindow({
                content: '<div id="content_name">'+ name + '</div>' + 
                          '<div id="content_address">'+ adds + '</div>' +
                          '<button id="keep" class="btn btn-primary btn-sm btn-block">キープ</button>'
            });
            const marker = new google.maps.Marker({
              position: location,
              map,
              title: name,
              icon: {
                url: "<%= asset_pack_path 'media/images/onsen.png' %>",
                scaledSize: new google.maps.Size(40, 40)
              },
            });
            marker.addListener("click", () => {
              infowindow.open(map, marker);
            });
            infowindow.addListener('domready', ()=> {
              document.getElementById('keep').addEventListener('click', ()=>{
                addElement();
              });
            });
          });
        }
      }
    }); 
  }

  function dragMarker(){
    google.maps.event.addListener(map, "drag", searchOnsen);
  }

  function addElement() {
    if (count <= 4) {
      var content_name = document.getElementById('content_name').innerText
      var content_address = document.getElementById('content_address').innerText

      var address = document.createElement("label")
      address.classList.add("invisible");
      address.innerText = content_address;

      var br = document.createElement("br")
      br.setAttribute('id', 'br_list');
  
      var element = document.createElement("label")
      element.classList.add("btn-block");
      element.classList.add("mt-2");
      element.setAttribute('id', 'keep_list');
      element.innerText = content_name;
  
      var parent = document.getElementById('parent')
      parent.appendChild(element);
      parent.appendChild(address);
      parent.appendChild(br);
      count += 1
      

    } else {
      alert("最大５つまでです。")
      content_name = ""
    }
    var keep_list = document.getElementById('keep_list')
    keep_list.setAttribute('id', 'keep_list' + count);
    var new_keep_list = document.getElementById('keep_list' + count)

    var move = document.createElement("button")
    move.classList.add("badge");
    move.classList.add("badge-danger");
    move.classList.add("ml-2");
    move.innerText = "移動";
    move.setAttribute('id', 'move');
    new_keep_list.appendChild(move);

    var move_badges = document.querySelectorAll('#move');
    for(var i = 0; i < move_badges.length; i++) {
      move_badges[i].addEventListener('click', moving, false);
    }
    
    content_name = ""
  }

  function moving(e){
    parentnode = e.target.parentNode
    address = parentnode.nextElementSibling.textContent;
    name = parentnode.textContent.replace("移動", "");;

    var geocoder = new google.maps.Geocoder();
    geocoder.geocode({
      address: name
    }, function(results, status) {
      if (status !== 'OK') {
        alert('該当する場所がございません。')
        return;
      }
      if (results[0]) {
      map = new google.maps.Map(target, {
          center: results[0].geometry.location,
          zoom: 15
        });
      } else {
        alert('該当する場所がございません。')
        return;
      }
      const infowindow = new google.maps.InfoWindow({
        content: '<div>'+ name + '</div>' +
                '<a>'+ address + '</a>'
      });

      var marker = new google.maps.Marker({
        position: map.getCenter(),
        map: map,
        icon: {
          url: "<%= asset_pack_path 'media/images/onsen.png' %>",
          scaledSize: new google.maps.Size(40, 40)
        },
      });

      marker.addListener("click", () => {
        infowindow.open(map, marker);
      });
      dragMarker();
    });
  }

  
</script>

app/views/shared/_footer.html.erb
<footer class="footer bg-success fixed-bottom">
  <p class="mb-0">2021.</p>
</footer> 

app/views/shared/_form.html.erb
<div class="form-area">
  <%= form_with(model: @map, class: 'js-form') do |f| %>
    <%= f.text_field :name, placeholder: "名前" %>
    <%= f.text_area :address, placeholder: "住所" %>
    <%= f.submit "お気に入り登録" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-success bg-success">
  <a class="navbar-brand text-dark" href="/">温泉マップ</a>
  <div id="open" class="btn">
    <span class="material-icons md-36 md-light">not_listed_location</span>
  </div>
  <div id="mask" class="hidden"></div>
  <section id="modal" class="hidden">
    <h2>このサイトについて</h2>
    <p>温泉マップは周辺の温泉、銭湯を表示するサービスです。</p>
    <p>地名・エリアから探すもしくは現在地周辺から探すことが可能です。</p>
    <p>探したい場所を表示させたら、スクロールやドラッグ等で周辺の温泉をお探しください。</p>
    <p>登録無しでもキープ(5件まで)可能ですが、温泉のお気に入り登録はユーザー登録が必要です。</p>
    
    <p>※テスト用にユーザーを用意致しました。ログイン画面に記載がございますので、是非ご活用ください。</p>
  
    <div id="close" class="btn btn-primary">閉じる</div>
  </section>
  <div class="input-group">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control" type="text" id="address" placeholder="地名・エリアから探す">
    </form>
    <div class="input-group-append">
      <button id="search" class="btn btn-outline-dark my-2 my-sm-0">移動</button>
    </div>
    <button id="cl" class="ml-sm-5 btn btn-outline-dark my-2 my-sm-0">現在地から探す</button>
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, class:"btn btn-outline-dark ml-3 my-2 my-sm-0" %>
      <%= link_to "お気に入り登録", new_map_path, class:"btn btn-outline-dark ml-3 my-2 my-sm-0" %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class:"btn btn-outline-dark ml-3 my-2 my-sm-0" %>
      <%= link_to "ユーザー登録", new_user_registration_path, class:"btn btn-outline-dark ml-3 my-2 my-sm-0" %>
      <%= link_to "お気に入り登録", new_map_path, class:"btn btn-outline-dark ml-3 my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<nav class="col-md-3 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <div class="d-flex flex-row">
          <div class="mt-3">キープ一覧(最大５つ)</div>
          <button id="reset" type="button" class="btn btn-secondary ml-3 mt-3 p-0">リセット</button>
        </div>
        <div id="parent" class="text-center">
        </div>
      </li>
    </ul>
  </div>
  <%= render "shared/form" %>
    <ul class="messages">
      <% @maps.each do |map| %>
        <li class="message"><%= map.name %></li>
      <% end %>
    </ul>
</nav>